apiVersion: v1
kind: Service
metadata:
  name: nodapp-service
spec:
  selector:
    app: nodeapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8080
      nodePort: 31110